spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.20.195.253:3306/big_event
    username: root
    password: 321321321
  data:
    redis:
      host: localhost
      port: 6379

mybatis:
  configuration:
    map-underscore-to-camel-case: true #底線命名to駝峰命名

CLOUDINARY_URL: cloudinary://449757555464192:ZUkdSt1y8lBldqJZEkeUIzNlrE4@dsfmt4qaq